name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc

      - name: Run Makefile test
        run: |
          poetry install
          poetry run coverage run -m pytest -p no:warnings
          poetry run coverage report -m --fail-under=85

      - name: Debug Information
        run: |
          python --version
          poetry --version
          pytest --version
          echo $PATH
      
      - name: Clean coverage files
        run: make clean-coverage
